{
 "title": "MacOS / logs",
 "tags": [ "macos-node-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({job=\"integrations/macos-node\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=\"integrations/macos-node\",job=~\"$job\"}, instance)"
   },
   {
    "name": "filename",
    "label": "Filename",
    "query": "label_values({job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}, filename)"
   },
   {
    "name": "sender",
    "label": "Sender",
    "query": "label_values({job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\",filename=~\"$filename\"}, sender)"
   },
   { "name": "regex_search", "label": "Regex search" },
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "stat",
   "description": "Shows if logs are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Latest logs received",
   "type": "stat",
   "description": "Shows the timestamp of the latest logs received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=~\"$job\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } }
  },
  {
   "title": "Logs volume",
   "type": "timeseries",
   "description": "Logs volume grouped by \"sender\" label.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (sender) (count_over_time({job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\",filename=~\"$filename\",sender=~\"$sender\"}\n|~ \"$regex_search\"\n\n[$__interval]))\n",
     "legendFormat": "{{ sender }}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\",filename=~\"$filename\",sender=~\"$sender\"} \n|~ \"$regex_search\"\n\n\n"
    }
   ]
  }
 ]
}