{
 "title": "MacOS / overview",
 "tags": [ "macos-node-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info{job=\"integrations/macos-node\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_uname_info{job=\"integrations/macos-node\",job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "stat",
   "description": "Shows if metrics are being received for the selected time range.",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1) and on() ((count(up{job=~\"$job\"} == 1) > 0) and (absent(absent(node_uname_info{job=~\"$job\"})))) or vector(0) and on() ((count(up{job=~\"$job\"}) > 0) and (absent(node_uname_info{job=~\"$job\"})))\n"
    }
   ]
  },
  {
   "title": "Latest metrics received",
   "type": "stat",
   "description": "Shows the timestamp of the latest metrics received for this integration in the last 24 hours.",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector(1) and on() ((count(up{job=~\"$job\"} == 1) > 0) and (absent(absent(node_uname_info{job=~\"$job\"})))) or vector(0) and on() ((count(up{job=~\"$job\"}) > 0) and (absent(node_uname_info{job=~\"$job\"})))\n"
    }
   ]
  },
  {
   "title": "Integration version",
   "type": "stat",
   "description": "Shows the installed version of this integration.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 3 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The duration of time that has passed since the last reboot or system start.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "stat",
   "description": "System's hostname.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Kernel version",
   "type": "stat",
   "description": "Kernel version of linux host.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "OS version",
   "type": "stat",
   "description": "Operating system",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "node_os_info{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}\n"
    }
   ]
  },
  {
   "title": "CPU count",
   "type": "stat",
   "description": "CPU count is the number of processor cores or central processing units (CPUs) in a computer,\ndetermining its processing capability and ability to handle tasks concurrently.\n",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without (cpu) (node_cpu_seconds_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "Cores"
    }
   ]
  },
  {
   "title": "Memory total",
   "type": "stat",
   "description": "Amount of random-access memory (RAM) installed.\nIt represents the system's available working memory that applications and the operating system use to perform tasks.\nA higher memory total generally leads to better system performance and the ability to run more demanding applications and processes simultaneously.\n",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_total_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Physical memory"
    }
   ]
  },
  {
   "title": "Total swap",
   "type": "stat",
   "description": "Total swap available.\n\nSwap is a space on a storage device (usually a dedicated swap partition or a swap file) \nused as virtual memory when the physical RAM (random-access memory) is fully utilized.\nSwap space helps prevent memory-related performance issues by temporarily transferring less-used data from RAM to disk,\nfreeing up physical memory for active processes and applications.\n",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_swap_total_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Root mount size",
   "type": "stat",
   "description": "Total capacity on the primary mount point /.\n",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\", mountpoint=\"/\", fstype!=\"rootfs\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 8 } },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "Total CPU utilization percent is a metric that indicates the overall level of central processing unit (CPU) usage in a computer system.\nIt represents the combined load placed on all CPU cores or processors.\n\nFor instance, if the total CPU utilization percent is 50%, it means that,\non average, half of the CPU's processing capacity is being used to execute tasks. A higher percentage indicates that the CPU is working more intensively, potentially leading to system slowdowns if it remains consistently high.\n",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count by (instance) (count(node_cpu_seconds_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))\n",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Total CPU utilization percent is a metric that indicates the overall level of central processing unit (CPU) usage in a computer system.\nIt represents the combined load placed on all CPU cores or processors.\n\nFor instance, if the total CPU utilization percent is 50%, it means that,\non average, half of the CPU's processing capacity is being used to execute tasks. A higher percentage indicates that the CPU is working more intensively, potentially leading to system slowdowns if it remains consistently high.\n",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\", mode=~\"idle|iowait|steal\"}[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})\n) * 100\n",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "description": "System load average over the previous 1, 5, and 15 minute ranges.\n\nA measurement of how many processes are waiting for CPU cycles. The maximum number is the number of CPU cores for the node.\n",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "count without (cpu) (node_cpu_seconds_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "Cores"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 15 } },
  {
   "title": "Memory usage",
   "type": "stat",
   "description": "RAM (random-access memory) currently in use by the operating system and running applications, in percent.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    (\n      avg(node_memory_internal_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}) -\n      avg(node_memory_purgeable_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}) +\n      avg(node_memory_wired_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}) +\n      avg(node_memory_compressed_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"})\n    ) /\n    avg(node_memory_total_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"})\n)\n*\n100\n"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "- Physical memory: Total amount of memory installed in this computer;\n- App memory: Physical memory allocated by apps and system processes;\n- Wired memory: Physical memory, containing data that cannot be compressed or swapped to disk;\n- Compressed memory: Physical memory used to store a compressed version of data that has not been used recently;\n- Swap used: Amount of compressed data temporarily moved to disk to make room in memory for more recently used data.\n",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_internal_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"} -\n  node_memory_purgeable_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"} +\n  node_memory_wired_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"} +\n  node_memory_compressed_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}\n)\n",
     "legendFormat": "Memory used"
    },
    {
     "expr": "node_memory_total_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Physical memory"
    },
    {
     "expr": "(\n    node_memory_internal_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"} -\n    node_memory_purgeable_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}\n)\n",
     "legendFormat": "App memory"
    },
    {
     "expr": "node_memory_wired_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Wired memory"
    },
    {
     "expr": "node_memory_compressed_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Compressed memory"
    },
    {
     "expr": "node_memory_swap_used_bytes{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Swap used"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 22 } },
  {
   "title": "Disk reads/writes",
   "type": "timeseries",
   "description": "Disk read/writes in bytes per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
     "legendFormat": "{{ device }} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
     "legendFormat": "{{ device }} written"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\", device!=\"\"}[$__rate_interval])",
     "legendFormat": "{{ device }} io util"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "table",
   "description": "Disk utilisation in percent, by mountpoint. Some duplication can occur if the same filesystem is mounted in multiple locations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype!=\"\", mountpoint!=\"\", job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "node_filesystem_avail_bytes{fstype!=\"\", mountpoint!=\"\", job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{ mountpoint }} free"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 31 } },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "Network traffic (bits per sec) measures data transmitted and received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8\n# only show interfaces that had traffic change at least once during selected dashboard interval:\nand\nincrease(\n    node_network_receive_bytes_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}[$__range]\n    ) > 0\n",
     "legendFormat": "{{ device }} received"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*8\n# only show interfaces that had traffic change at least once during selected dashboard interval:\nand\nincrease(\n    node_network_transmit_bytes_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}[$__range]\n    ) > 0\n",
     "legendFormat": "{{ device }} transmitted"
    }
   ]
  },
  {
   "title": "Network errors and dropped packets",
   "type": "timeseries",
   "description": "**Network errors**:\n\nNetwork errors refer to issues that occur during the transmission of data across a network. \n\nThese errors can result from various factors, including physical issues, jitter, collisions, noise and interference.\n\nMonitoring network errors is essential for diagnosing and resolving issues, as they can indicate problems with network hardware or environmental factors affecting network quality.\n\n**Dropped packets**:\n\nDropped packets occur when data packets traveling through a network are intentionally discarded or lost due to congestion, resource limitations, or network configuration issues. \n\nCommon causes include network congestion, buffer overflows, QoS settings, and network errors, as corrupted or incomplete packets may be discarded by receiving devices.\n\nDropped packets can impact network performance and lead to issues such as degraded voice or video quality in real-time applications.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])>0",
     "legendFormat": "{{ device }} errors transmitted"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])>0",
     "legendFormat": "{{ device }} errors received"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])>0",
     "legendFormat": "{{ device }} transmitted dropped"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=\"integrations/macos-node\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])>0",
     "legendFormat": "{{ device }} received dropped"
    }
   ]
  }
 ]
}